// ---------------------------------------------------------------------------
// DO NOT EDIT THIS FILE!
//
// This file is automatically generated by `build.rs`. It collects all Rust
// code snippets from the `.mdx` documentation files and turns them into
// runnable tests.
//
// Any manual edits will be overwritten on the next `cargo build` or `cargo test`.
//
// To make changes, edit the Rust snippets in the `.mdx` files directly.
// ---------------------------------------------------------------------------
