name: deploy docs
on:
  push:
    branches:
      - 'master'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: call-build
    runs-on: ubuntu-latest
    steps:
      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Download static doc files
        uses: actions/download-artifact@v5
        with:
          name: github-pages
          path: .

      - name: Upload static doc files to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: .
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4





      
