name: Documentation Build/Test/Deploy
on:
  workflow_dispatch:
  push:
    branches: 
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - uses: oven-sh/setup-bun@v2
        with: 
          bun-version: "1.3.0"
      - run: bun install
      - name: Build Docs
        run: bunx vocs build
      - name: Upload Docs to Pages
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: src/dist
          include-hidden-files: true

  test-rust-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test-rust-code
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --message-format human

  deploy:
    needs: [build, test-rust-code]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy from pages storage
        id: deployment
        uses: actions/deploy-pages@v4



      
